version: "3.7"

services:
  api:
    build: 
      context: ./api
    container_name: api
    environment: 
     - CONNECTION_STRING=postgres://postgres:postgres@db/postgres-db
    depends_on:
     - db
    command: node index.js
    volumes:
      - ./api:/api
    ports:
      - "3001:3001"
    networks:
      - privet-nw
      - puplic-nw

  web:
    build: 
      context: ./web
    container_name: web
    environment:
      - API_URL=http://api:3001/data
    volumes:
      - ./web:/web
    depends_on:
      - api
    command: node index.js
    ports:
      - "80:3000"
    networks:
      - puplic-nw

  db:
    image: postgres:11.2-alpine
    ports: ["5432"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres-db"
    volumes:
      - "/home/ubuntu/english2arabic/sql_scripts/:/docker-entrypoint-initdb.d"
    networks:
      - privet-nw

networks:
  privet-nw:  #api
      driver: bridge
  puplic-nw:  #web
      driver: bridge